site_name: "Data Agents"
repo_url: https://github.com/encord-team/encord-agents
colab_prefix: https://colab.research.google.com/github/encord-team/encord-agents
branch_name: main # used for debugging should be "main"

watch:
  - encord_agents

theme:
  logo: assets/logo_single.png
  favicon: assets/favicon.png
  name: "material"
  custom_dir: docs/overrides
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    #    - navigation.expand
    # - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow

nav:
  - "Basics":
      - "Home": index.md
      - "Authentication": authentication.md
      - "Get Started":
          - "Installation": installation.md
          - "Basic Example": basic_example.md
      - "Dependencies": dependencies.md
  - "Editor Agents":
      - "Overview": editor_agents/index.md
      - "GCP Cloud Functions": editor_agents/gcp.md
      - "FastAPI": editor_agents/fastapi.md
      - "Hosting with Modal": editor_agents/modal.md
      - "Examples": editor_agents/examples/index.md
  - "Task Agents":
      - "Overview": task_agents/index.md
      - "Execution":
          - "Execution intro": task_agents/runner_intro.md
          - "Sequential": task_agents/sequential_runner.md
          - "Multi-processing (queues)": task_agents/queue_runner.md
      - "Examples":
          - "Prioritize Annotation Tasks": notebooks/task_agent_set_priority.ipynb
          - "Transfer labels to a twin project": notebooks/twin_project_label_transfer.ipynb
          - "Pre-label videos with bounding boxes": notebooks/prelabel_videos_with_bounding_boxes.ipynb
          - "Pre-label videos with Mask-RCNN": notebooks/mask_rcnn_on_videos.ipynb
          - "Use models from Hugging Face 🤗": notebooks/hugging_face_agent_example.ipynb
          - "Use YOLO model from Ultralytics": notebooks/yolo_example.ipynb
          - "Transcribe multi-speaker conversations": notebooks/audio_transcription_agent_multi_speaker.ipynb
          - "Sentiment analysis": notebooks/sentiment_analysis.ipynb
          - "Multimodal LLM as a Judge": notebooks/llm_as_a_judge.ipynb
          - "Multistage VLM video captioning": notebooks/multistage_video_summarisation.ipynb
  - "Reference":
      - "Editor agents": reference/editor_agents.md
      - "Task agents": reference/task_agents.md
      - "Core": reference/core.md


extra:
  homepage: https://encord.com

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - codeinclude
  - git-revision-date-localized: # Shows last update date
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            show_if_no_docstring: true
            heading_level: 3
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
            show_submodules: true
            separate_signature: true
            show_signature_annotations: true
            line_length: 60
            docstring_section_style: list
            show_docstring_yields: true
            show_docstring_examples: true
  - glightbox
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: true
  - macros
