site_name: "Encord Agents"
repo_url: https://github.com/encord-team/encord-agents
colab_prefix: https://colab.research.google.com/github/encord-team/encord-agents
branch_name: feat/colab-task-examples # used for debugging should be "main"

watch:
  - encord_agents

theme:
  logo: assets/logo_single.png
  favicon: assets/favicon.png
  name: "material"
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand

nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Authentication": authentication.md
  - "Getting started": getting_started.md
  - "Dependencies": dependencies.md
  - "Editor Agents":
      - "Intro": editor_agents/index.md
      - "GCP Cloud Functions": editor_agents/gcp.md
      - "FastAPI": editor_agents/fastapi.md
      - "Examples": editor_agents/examples/index.md
  - "Task Agents":
      - "Intro": task_agents/index.md
      - "Execution": task_agents/runner.md
      - "Examples":
          - Prioritize Annotation Tasks: notebooks/task_agent_set_priority.ipynb
          - Transfer labels to a twin project: notebooks/twin_project_label_transfer.ipynb
          - Pre-label videos with bounding boxes: notebooks/prelabel_videos_with_bounding_boxes.ipynb
  - "Reference":
      - "Editor agents": reference/editor_agents.md
      - "Task agents": reference/task_agents.md
      - "Core": reference/core.md

extra:
  homepage: https://encord.com

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - codeinclude
  - git-revision-date-localized: # Shows last update date
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            show_if_no_docstring: true
            heading_level: 3
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
            show_submodules: true
            separate_signature: true
            show_signature_annotations: true
            line_length: 60
            docstring_section_style: list
            show_docstring_yields: true
            show_docstring_examples: true
  - glightbox
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: true
