site_name: "Encord Agents"

watch:
  - encord_agents

theme:
  logo: assets/logo_single.png
  favicon: assets/favicon.png
  name: "material"

nav:
  - "Home": index.md
  - "Editor Agents":
      - "Intro": editor_agents/index.md
      - "Reference": editor_agents/reference.md
  - "Task Agents": task_agents/index.md
  - "Reference":
      - "Editor agents": reference/editor_agents.md
      - "Task agents": reference/task_agents.md
      - "Core": reference/core.md

extra:
  homepage: https://encord.com

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            show_if_no_docstring: true
            heading_level: 3
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
            show_submodules: true
            separate_signature: true
            show_signature_annotations: true
            line_length: 60
            docstring_section_style: list
            show_docstring_yields: true
            show_docstring_examples: true
