site_name: "Encord Agents"
repo_url: https://github.com/encord-team/encord-agents

watch:
  - encord_agents

theme:
  logo: assets/logo_single.png
  favicon: assets/favicon.png
  name: "material"
  features:
    - content.code.copy

nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Authentication": authentication.md
  - "Getting started": getting_started.md
  - "Editor Agents":
      - "Intro": editor_agents/index.md
      - "Examples": editor_agents/examples
  - "Task Agents":
      - "Intro": task_agents/index.md
      - "Examples": task_agents/examples
  - "Reference":
      - "Editor agents": reference/editor_agents.md
      - "Task agents": reference/task_agents.md
      - "Core": reference/core.md

extra:
  homepage: https://encord.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            show_if_no_docstring: true
            heading_level: 3
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
            show_submodules: true
            separate_signature: true
            show_signature_annotations: true
            line_length: 60
            docstring_section_style: list
            show_docstring_yields: true
            show_docstring_examples: true
  - glightbox
