name: "Setup test environment"
description: "Sets up Python, Poetry and dependencies"

inputs:
  python:
    description: "Python version to use"
    default: 3.11.6
    required: false
  poetry:
    description: "Poetry version to use"
    default: 1.8.3
    required: false

runs:
  using: "composite"

  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry }}
        virtualenvs-in-project: true

    - id: cached-poetry
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}-${{ env.pythonLocation }}-${{ inputs.poetry }}

    - if: steps.cached-poetry.outputs.cache-hit != 'true'
      run: |
        poetry lock --no-update
        poetry install --no-interaction
      shell: bash

    - name: Clear lint cache
      run: |
        rm -rf /home/runner/work/encord-agents/encord-agents/.ruff_cache
      shell: bash
