on:
  push:
    branches:
      - main
  schedule:
    # Schedule the workflow to run at 9:40 AM UK time
    - cron: '40 9 * * *'
name: Aikido Scan
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:v1.0.52
    steps: 
      - uses: actions/checkout@v4 

      - name: Run scan
        run: aikido-local-scanner scan ./ --apikey ${{ secrets.AIKIDO_API_Key }} --repositoryname encord-agents --branchname main
